version: "3.3"

services:

  generate:
    image: python:3.7
    volumes:
      - ./:/project
      - cache:/root/.cache/pip
    working_dir: /project/rchain_grpc
    entrypoint: ./generate.sh
    environment:
      RNODE_RELEASE: 0.7

  tests:
    image: python:3.7
    networks:
      - tests
    depends_on:
      - tests-rchain
    volumes:
      - ./:/project
      - cache:/root/.cache/pip
    environment:
      - RCHAIN_GRPC_HOST=tests-rchain
    working_dir: /project
    entrypoint: ./run_tests.sh

  tests-rchain:
    networks:
      - tests
    build:
      context: ./rchain
      dockerfile: ./Dockerfile

networks:
  tests:

volumes:
  cache:
